container:
  image: debian:latest
  cpu: 8
  memory: 32G

task:
  script: |
    mkdir -p ~/bin/repo
    curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo
    apt install git-core
    mkdir ~/OrangeFox_10 && cd ~/OrangeFox_10 && git clone https://gitlab.com/OrangeFox/sync.git
