container:
  image: debian:latest
  cpu: 8
  memory: 32G

task:
  script: |
    apt update && apt install -y git-core gnupg make curl flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig
    git config --global user.email "tukaiari@gmail.com" && git config --global user.name "Arijit Roy"
    mkdir ~/bin
    PATH=~/bin:$PATH && curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
    chmod a+x ~/bin/repo
    mkdir ~/an
    cd ~/an
    repo init -u https://github.com/ArrowOS/android_manifest.git -b arrow-11.0 && repo sync
